import { Elysia, type ValidationError } from "elysia";
import { InternalError, NotFoundError } from "@//shared/errors";
import { logger } from "@/config/logger";
import {
  InternalErrorModel,
  NotFoundErrorModel,
  ValidationErrorModel,
} from "@/shared/errors/model";
import { createInternalError, formatValidationDetails } from "@/shared/errors/utils";

export const errorHandlerPlugin = new Elysia({ name: "error" })
  .error({
    NOT_FOUND: NotFoundError,
    INTERNAL_ERROR: InternalError,
  })
  .model({
    ValidationError: ValidationErrorModel,
    NotFoundError: NotFoundErrorModel,
    InternalError: InternalErrorModel,
  })
  .onError({ as: "global" }, ({ code, error, request, set }) => {
    const url = new URL(request.url);

    const isValidation = code === "VALIDATION";
    const validationError = isValidation ? (error as ValidationError) : null;
    const isResponseValidation = isValidation && validationError?.type === "response";

    const message = isValidation
      ? `Validation failed on ${validationError?.type || "unknown"}`
      : error instanceof Error
        ? error.message
        : "Unknown error";

    const details = isValidation ? validationError?.all : undefined;
    const logLevel = code === "INTERNAL_ERROR" || isResponseValidation ? "error" : "warn";

    logger[logLevel](
      { method: request.method, path: url.pathname, code, message, details },
      "request failed",
    );

    switch (code) {
      case "NOT_FOUND":
        set.status = 404;
        return {
          status: 404 as const,
          code: "NOT_FOUND" as const,
          message,
        };

      case "VALIDATION":
        if (isResponseValidation) {
          set.status = 500;
          return createInternalError("Invalid response payload generated by the server");
        }

        set.status = 400;
        return {
          status: 400 as const,
          code: "VALIDATION" as const,
          message: "Invalid request data",
          details: formatValidationDetails(validationError?.all),
        };

      default:
        set.status = 500;
        return createInternalError(message);
    }
  });
